-- Create the submissions table with a status column
CREATE TABLE public.submissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  status text NOT NULL DEFAULT 'Aguardando resposta',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security for the submissions table
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow public read access to all submissions
CREATE POLICY "Enable read access for all users" ON public.submissions
  FOR SELECT USING (true);

-- Create a policy to allow public insert access for all submissions
CREATE POLICY "Enable insert for all users" ON public.submissions
  FOR INSERT WITH CHECK (true);

-- Create a policy to allow public update access on the status column
CREATE POLICY "Enable update for all users" ON public.submissions
  FOR UPDATE USING (true);
